% Day 2 - Elliptical Orbit - Kepler Dynamics
Create Spacecraft Sat;
Sat.DateFormat        = UTCGregorian;
Sat.Epoch             = '01 Jan 2025 00:00:00.000';
Sat.CoordinateSystem  = EarthMJ2000Eq;
Sat.DisplayStateType  = Keplerian;
Sat.SMA               = 6976;    % km
Sat.ECC               = 0.001;      % highly elliptical
Sat.INC               = 97.8;
Sat.RAAN              = 0;
Sat.AOP               = 0;
Sat.TA                = 0;        % start AT periapsis
Sat.DryMass           = 850;
Sat.Cd                = 2.2;
Sat.DragArea          = 15;

Create ForceModel EarthFM;
EarthFM.CentralBody                = Earth;
EarthFM.PrimaryBodies              = {Earth};
EarthFM.PointMasses                = {Luna, Sun};
EarthFM.SRP                        = On;
EarthFM.GravityField.Earth.Degree  = 10; %higher value to see J2 RAAN effect
EarthFM.GravityField.Earth.Order   = 10;

Create Propagator EarthProp;
EarthProp.FM              = EarthFM;
EarthProp.Type            = RungeKutta89;
EarthProp.InitialStepSize = 60;

%--- ORBIT VIEW ---
Create OrbitView MyOrbitView;
MyOrbitView.Add               = {Sat, Earth};
MyOrbitView.CoordinateSystem  = EarthMJ2000Eq;
MyOrbitView.ViewPointVector   = [ 20000 0 0 ];
MyOrbitView.ShowLabels        = true;
MyOrbitView.EnableStars       = On;

%--- GROUND TRACK ---
Create GroundTrackPlot MyGroundTrack;
MyGroundTrack.Add             = {Sat};
MyGroundTrack.CentralBody     = Earth;

Create ReportFile rf;
rf.Filename     = 'D:\Space Softwares\GMAT Project\Elliptical Orbit + SSO Analysis\Output\SSO_data.txt';
rf.Add          = {Sat.ElapsedSecs, Sat.Earth.RMAG, Sat.Earth.Latitude, Sat.Earth.Longitude, Sat.EarthMJ2000Eq.RAAN, Sat.VX, Sat.VY, Sat.VZ};
rf.WriteHeaders = true;

BeginMissionSequence;
Propagate EarthProp(Sat) {Sat.ElapsedDays = 10};   % ~1 orbital period